version: '3.8'

services:
  web:
    build: ./SearchApp
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./SearchApp/:/usr/src/SearchApp
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev