version: '3.8'

services:
  web:
    image: "dilreni2137/search-app:prod"
    mem_limit: 128m
    command: gunicorn SearchApp.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
