name: Deploy app to AWS EB

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Generate deployment package
      run: zip deploy.zip ./docker-compose.yml

    - name: Deploy to EBS
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: search-app
        environment_name: Search-app-env-2
        version_label: "search-app v1.0.0"
        region: eu-central-1
        deployment_package: deploy.zip
