name: Publish Docker image

on:
  # release:
  #   types: [published]
  # push:
  #   branches:
  #     - 'main'
  workflow_dispatch:

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Buildx set-up
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build dev and push
      uses: docker/build-push-action@v3
      with:
        context: SearchApp
        file: ./SearchApp/Dockerfile.dev
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/search-app:dev
        build-args: "SECRET_KEY=${{ secrets.SECRET_KEY }}"

    - name: Build prod and push
      uses: docker/build-push-action@v3
      with:
        context: SearchApp
        file: ./SearchApp/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/search-app:prod
        build-args: "SECRET_KEY=${{ secrets.SECRET_KEY }}"
